create table AppUser (
                         id int primary key generated by default as identity,
                         username varchar (100),
                         email varchar(100) not null,
                         password varchar(100)
);

insert into AppUser (username, email, password) VALUES ('test_user', 'test_user_email@email.com', 'password');